Repository TheHikuro/ESGI-ASSOCIATIONS, pull requests merged in 2022-06, with the labels that each got.

#5 Add JWT to project to login + hash register
  .docker/conf/.env.local
  .docker/conf/.gitignore
  .docker/conf/php-fpm/sites-enabled/default.conf
  Makefile
  Web.API/.env
  Web.API/.gitignore
  Web.API/composer.json
  Web.API/composer.lock
  Web.API/config/bundles.php
  Web.API/config/jwt/.gitignore
  Web.API/config/packages/lexik_jwt_authentication.yaml
  Web.API/config/packages/security.yaml
  Web.API/config/packages/web_profiler.yaml
  Web.API/config/routes.yaml
  Web.API/config/routes/api_platform.yaml
  Web.API/config/routes/web_profiler.yaml
  Web.API/migrations/Version20220531105619.php
  Web.API/public/.htaccess
  Web.API/src/Controller/SecurityController.php
  Web.API/src/DataPersister/UserDataPersister.php
  Web.API/src/Entity/Association.php
  Web.API/src/Entity/Event.php
  Web.API/src/Entity/Section.php
  Web.API/src/Entity/User.php
  Web.API/src/Security/LoginAuthenticator.php
  Web.API/symfony.lock
  Web.API/templates/security/login.html.twig
Labels: enhancement

#6 Add login interface for api doc / requests
  Web.API/config/packages/security.yaml
  Web.API/src/Controller/SecurityController.php
  Web.API/src/Security/RequestMatcher/ApiLoginRequestMatcher.php
  Web.API/templates/security/login.html.twig
Labels: enhancement

#8 Add Account confirmation
  .docker/conf/.env.local
  Web.API/.env
  Web.API/composer.json
  Web.API/composer.lock
  Web.API/config/bundles.php
  Web.API/config/packages/api_platform.yaml
  Web.API/config/packages/dev/swiftmailer.yaml
  Web.API/config/packages/swiftmailer.yaml
  Web.API/config/packages/test/swiftmailer.yaml
  Web.API/migrations/Version20220601143747.php
  Web.API/migrations/Version20220602082929.php
  Web.API/migrations/Version20220602082947.php
  Web.API/src/Controller/User/ConfirmationEmailController.php
  Web.API/src/Controller/User/ValidateAccountController.php
  Web.API/src/Entity/Association.php
  Web.API/src/Entity/Event.php
  Web.API/src/Entity/Section.php
  Web.API/src/Entity/User.php
  Web.API/src/EventSubscriber/SectionSlugUpdater.php
  Web.API/src/EventSubscriber/UserResolver.php
  Web.API/symfony.lock
Labels: enhancement

#9 Fix send user email doc
  Web.API/src/Entity/User.php
Labels: bug

#10 Remove User unused route
  Web.API/src/Entity/User.php
Labels: bug

#11 Fix Route Permissions For Register & Sections
  Web.API/config/packages/security.yaml
  Web.API/src/Entity/User.php
Labels: bug

#13 Fix secured routes
  Web.UI/src/App.tsx
  Web.UI/src/api/apiUtils.ts
  Web.UI/src/components/Loader.tsx
  Web.UI/src/pages/FirstConnectionPage.tsx
  Web.UI/src/pages/LoginPage.tsx
  Web.UI/src/routes/private.tsx
  Web.UI/src/routes/public.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/StoreContext.tsx
  Web.UI/src/utils/context/actions/auth.ts
  Web.UI/src/utils/context/actions/loader.ts
  Web.UI/src/utils/context/reducers/auth.ts
  Web.UI/src/utils/context/reducers/loading.tsx
Labels: bug

#14 Add some User data into login api
  Web.API/config/services.yaml
  Web.API/src/EventListener/AuthenticationSucessListener.php
Labels: enhancement

#15 Add associations count to login api
  Web.API/src/EventListener/AuthenticationSucessListener.php
Labels: enhancement

#16 Feature/workflow first log api
  Web.UI/src/api/login.axios.api.ts
  Web.UI/src/api/users.axios.api.ts
  Web.UI/src/components/Input.tsx
  Web.UI/src/components/Stepper.tsx
  Web.UI/src/pages/FirstConnectionPage.tsx
  Web.UI/src/pages/HomePage.tsx
  Web.UI/src/pages/LoginPage.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/actions/auth.ts
  Web.UI/src/utils/context/actions/user.ts
  Web.UI/src/utils/context/reducers/auth.ts
  Web.UI/src/utils/context/reducers/user.ts
Labels: enhancement

#19 Fix psr4 error of AuthenticationSuccessListener
  Web.API/src/EventListener/AuthenticationSuccessListener.php
Labels: bug

#20 Update README.md
  README.md
Labels: documentation

#21 Update README.md
  README.md
Labels: documentation

#23 Fix api permissions for all entities
  Web.API/src/Entity/Association.php
  Web.API/src/Entity/Event.php
  Web.API/src/Entity/Section.php
  Web.API/src/Entity/User.php
Labels: bug

#24 Add avatar upload for User & Associations
  Web.API/composer.json
  Web.API/composer.lock
  Web.API/config/bundles.php
  Web.API/config/packages/api_platform.yaml
  Web.API/config/packages/vich_uploader.yaml
  Web.API/migrations/Version20220624193331.php
  Web.API/migrations/Version20220624204745.php
  Web.API/migrations/Version20220624222723.php
  Web.API/migrations/Version20220624231249.php
  Web.API/migrations/Version20220624231441.php
  Web.API/public/media/.gitignore
  Web.API/public/media/.gitkeep
  Web.API/public/media/associations/.gitkeep
  Web.API/public/media/users/.gitkeep
  Web.API/src/Controller/Association/DeleteAvatarController.php
  Web.API/src/Controller/Association/PostAvatarController.php
  Web.API/src/Controller/User/DeleteAvatarController.php
  Web.API/src/Controller/User/PostAvatarController.php
  Web.API/src/Entity/Association.php
  Web.API/src/Entity/User.php
  Web.API/src/Serializer/AssociationPostAvatarNormalizer.php
  Web.API/src/Serializer/UserPostAvatarNormalizer.php
  Web.API/symfony.lock
Labels: enhancement

#26 Add global mail route & fix entity denormalization
  Web.API/src/Controller/User/SendGLobalEmailController.php
  Web.API/src/Entity/Association.php
  Web.API/src/Entity/Event.php
  Web.API/src/Entity/Section.php
  Web.API/src/Entity/User.php
Labels: enhancement

#27 Front/card assos
  .gitignore
  .vscode/settings.json
  Web.API/composer.json
  Web.API/src/.DS_Store
  Web.API/src/Entity/User.php
  Web.UI/package.json
  Web.UI/src/api/apiUtils.ts
  Web.UI/src/api/assos.axios.ts
  Web.UI/src/api/login.axios.api.ts
  Web.UI/src/api/sections.axios.ts
  Web.UI/src/api/users.axios.api.ts
  Web.UI/src/components/Card.tsx
  Web.UI/src/components/Dashboard.tsx
  Web.UI/src/components/FormData.tsx
  Web.UI/src/components/Input.tsx
  Web.UI/src/components/Layout.tsx
  Web.UI/src/components/Navbar.tsx
  Web.UI/src/components/Table.tsx
  Web.UI/src/main.tsx
  Web.UI/src/pages/Admin/AdminPage.tsx
  Web.UI/src/pages/Admin/AssosAdminPage.tsx
  Web.UI/src/pages/Admin/EventsAdminPage.tsx
  Web.UI/src/pages/Admin/MailerAdminPage.tsx
  Web.UI/src/pages/Admin/SectionsAdminPage.tsx
  Web.UI/src/pages/Admin/UserAdminPage.tsx
  Web.UI/src/pages/AdminPage.tsx
  Web.UI/src/pages/AssosPage.tsx
  Web.UI/src/pages/RegisterPage.tsx
  Web.UI/src/routes/routes.tsx
  Web.UI/src/utils/context/StoreContext.tsx
  Web.UI/src/utils/context/actions/admin.ts
  Web.UI/src/utils/context/actions/assos.ts
  Web.UI/src/utils/context/actions/section.ts
  Web.UI/src/utils/context/actions/user.ts
  Web.UI/src/utils/context/reducers/admin.ts
  Web.UI/src/utils/context/reducers/assos.ts
  Web.UI/src/utils/context/reducers/sections.ts
  Web.UI/src/utils/context/reducers/user.ts
  Web.UI/src/utils/helpers/enums.ts
  Web.UI/yarn.lock
Labels: enhancement
